import java.util.Calendar;
import java.util.Set;

/**
 * An implementation of FutureMeeting for use with ContactManager. Unique IDs are generated by CM. 
 * @author markkingsbury
 */

public class FutureMeetingImpl extends MeetingImpl implements FutureMeeting {
	
	/**
	 * This constructor uses the constructor of the abstract class MeetingImpl.
	 * @param meetingId the meeting's ID (generated by ContactManager)
	 * @param meetingContacts the contacts taking part in the meeting
	 * @param scheduledDate the date of the meeting
	 */
	public FutureMeetingImpl(int meetingId, Set<Contact> meetingContacts, Calendar scheduledDate) {
		super(meetingId, meetingContacts, scheduledDate);
	}
	
	// No methods here, this is just a naming interface
	// (i.e. only necessary for type checking and/or downcasting)
}
