import java.util.Calendar;
import java.util.Set;

/**
 * An implementation of PastMeeting for use with ContactManager. Unique IDs are generated by CM. 
 * @author markkingsbury
 */

public class PastMeetingImpl extends MeetingImpl implements PastMeeting {
	
	private String meetingNotes;

	/**
	 * This constructor uses the constructor of the abstract class MeetingImpl.
	 * Additional functionality to add meeting note text is included here. 
	 * @param meetingId the meeting's ID (generated by ContactManager)
	 * @param contacts the contacts attending the meeting
	 * @param date the date of the meeting
	 * @param text, the notes to be added about the meeting
	 */
	public PastMeetingImpl (int meetingId, Set<Contact> contacts, Calendar date,
			String text) {
		super(meetingId, contacts, date);
		this.meetingNotes = text;
	}
	
	@Override
	public String getNotes() {
		return meetingNotes;
	}
}
